/**
 * Constants for handover feature
 */

export const HANDOVER_CONSTANTS = {
  CLASSIFICATION: 'Strictly Confidential – Internal Use Only',
  DOCUMENT_TITLE: 'DSK GLOBAL – PROJECT HANDOVER MEMO',
  MIN_BACKGROUND_LENGTH: 20,
  TOTAL_SECTIONS: 11,
} as const;

export const SECTION_NAMES = {
  1: 'PROJECT INFORMATION',
  2: 'BACKGROUND SUMMARY',
  3: 'FINALIZED SCOPE OF WORK',
  4: 'FEE STRUCTURE & PAYMENT TERMS',
  5: 'CLIENT-PROVIDED DOCUMENTS',
  6: 'DATA REQUIREMENTS (OUTSTANDING)',
  7: 'KEY RISKS / RED FLAGS',
  8: 'COMMUNICATION PROTOCOL',
  9: 'PROJECT TEAM ASSIGNMENT',
  10: 'HANDOVER CHECKLIST',
  11: 'SIGN-OFF',
} as const;
